### PR TITLE
navigate help maker R script to ST3

### PR DESCRIPTION
**Pull request by maxheld83**

### CODE REVIEW

**Comment by jlegewie** [comment]
Thanks.

**Comment by maxheld83** [comment]
sure thing @jlegewie 
I noticed only after the fact that there was a dedicated `ST3` branch, hope this was in the right place.
Is `master` branch now ready for ST3?

**Comment by jlegewie** [comment]
No, the master branch is for ST2 and the ST3 branch for ST3. That way package control serves the correct version.

**Comment by maxheld83** [comment]
uh ok – then maybe you might want to revert this PR, since I changed it to ST3 on master ...

**Comment by jlegewie** [comment]
Jep, I didn't even think about it because I haven't looked at master for such a long time...

**Pull request merged**
